function PrivacyPolicy(){var U='',Cb='" for "gwt:onLoadErrorFn"',Ab='" for "gwt:onPropertyErrorFn"',nb='"><\/script>',cb='#',Kb='&',tc='.cache.html',eb='/',qb='//',cc='0B7C64D5E2672A293D36C9D87A0AAF68',dc='0BA6BE6F6C2D533AEF5B1DF7839943C0',ec='0FDA6DF70D222505E8C49437E4AA7B3C',fc='11F96A09C8EB4321D9297D600A7A4266',hc='41BBAF19D83FA4A18DC3D689048B78CB',ic='427E60FE2D581EC8882DF06C05809E70',jc='7026E53892F19C490030DD0DAF6BAF73',kc='78FA021EEAE57910ED60F25674903CF6',lc='7F967960F19DE263B5777CCC8A93D7A9',mc='8247BBC2F360E2BDA32DDF0BE4DE5C6D',nc='9E1967EDAFE26F53C28372C22BACED3D',sc=':',ub='::',Mb=';',Bc='<script defer="defer">PrivacyPolicy.onInjectionDone(\'PrivacyPolicy\')<\/script>',mb='<script id="',xb='=',db='?',oc='A782C996C6C51D18A709D3ACD51CA8AA',zb='Bad handler "',pc='C4B4515CEB155EB634507E2D945AD3EF',qc='D97180F31BD9A55F21446E6272060EBA',Ac='DOMContentLoaded',rc='F7B653161B9EA0E8E769EF6813F027A6',V='PrivacyPolicy',jb='PrivacyPolicy.nocache.js',tb='PrivacyPolicy::',ob='SCRIPT',Pb='Unexpected exception in locale detection, using default: ',Ob='_',Nb='__gwt_Locale',lb='__gwt_marker_PrivacyPolicy',pb='base',hb='baseUrl',Y='begin',X='bootstrap',gb='clear.cache.gif',wb='content',Ib='default',bb='end',bc='fr',Xb='gecko',Yb='gecko1_8',Z='gwt.codesvr=',$='gwt.hosted=',_='gwt.hybrid',uc='gwt/standard/standard.css',Bb='gwt:onLoadErrorFn',yb='gwt:onPropertyErrorFn',vb='gwt:property',Lb='gwtLocale=',zc='head',_b='hosted.html?PrivacyPolicy',yc='href',Ub='ie10',Wb='ie8',Vb='ie9',Db='iframe',fb='img',Eb="javascript:''",vc='link',$b='loadExternalRefs',Hb='locale',Jb='locale=',rb='meta',Gb='moduleRequested',ab='moduleStartup',Tb='msie',sb='name',gc='nl',Fb='position:absolute;width:0;height:0;border:none',wc='rel',Sb='safari',ib='script',ac='selectingPermutation',W='startup',xc='stylesheet',kb='undefined',Zb='unknown',Qb='user.agent',Rb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=U,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:Y});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Z)!=-1||(c.indexOf($)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(_)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(V);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return M(a)}}PrivacyPolicy=null;c.gwtOnLoad(C,V,t,B);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:bb})}}
function H(){function e(a){var b=a.lastIndexOf(cb);if(b==-1){b=a.length}var c=a.indexOf(db);if(c==-1){c=a.length}var d=a.lastIndexOf(eb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(fb);b.src=a+gb;a=e(b.src)}return a}
function g(){var a=K(hb);if(a!=null){return a}return U}
function h(){var a=n.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(jb)!=-1){return e(a[b].src)}}return U}
function i(){var a;if(typeof isBodyLoaded==kb||!isBodyLoaded()){var b=lb;var c;n.write(mb+b+nb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ob){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return U}
function j(){var a=n.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return U}
function k(){var a=n.location;return a.href==a.protocol+qb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==U){l=h()}if(l==U){l=i()}if(l==U){l=j()}if(l==U&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(rb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(sb),g;if(f){f=f.replace(tb,U);if(f.indexOf(ub)>=0){continue}if(f==vb){g=e.getAttribute(wb);if(g){var h,i=g.indexOf(xb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=U}u[f]=h}}else if(f==yb){g=e.getAttribute(wb);if(g){try{D=eval(g)}catch(a){alert(zb+g+Ab)}}}else if(f==Bb){g=e.getAttribute(wb);if(g){try{C=eval(g)}catch(a){alert(zb+g+Cb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function M(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var N;function O(){if(!N){N=true;var a=n.createElement(Db);a.src=Eb;a.id=V;a.style.cssText=Fb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:Gb});a.contentWindow.location.replace(t+Q)}}
w[Hb]=function(){var b=null;var c=Ib;try{if(!b){var d=location.search;var e=d.indexOf(Jb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Kb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=n.cookie;var i=h.indexOf(Lb);if(i>=0){var g=h.indexOf(Mb,i);if(g<0){g=h.length}b=h.substring(i+10,g)}}if(!b){b=K(Hb)}if(!b){b=m[Nb]}if(b){c=b}while(b&&!J(Hb,b)){var j=b.lastIndexOf(Ob);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Pb+a)}m[Nb]=c;return b||Ib};v[Hb]={'default':0,fr:1,nl:2};w[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=10}())return Ub;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=9}())return Vb;if(function(){return b.indexOf(Tb)!=-1&&n.documentMode>=8}())return Wb;if(function(){return b.indexOf(Xb)!=-1}())return Yb;return Zb};v[Qb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};PrivacyPolicy.onScriptLoad=function(){if(N){r=true;G()}};PrivacyPolicy.onInjectionDone=function(){q=true;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:bb});G()};I();H();var P;var Q;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(V))){m.location.reload();return}Q=_b;P=U}o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:ac});if(!F()){try{L([bc,Yb],cc);L([Ib,Sb],dc);L([Ib,Vb],ec);L([bc,Vb],fc);L([gc,Sb],hc);L([bc,Ub],ic);L([gc,Yb],jc);L([Ib,Wb],kc);L([gc,Wb],lc);L([Ib,Yb],mc);L([bc,Wb],nc);L([gc,Vb],oc);L([Ib,Ub],pc);L([bc,Sb],qc);L([gc,Ub],rc);P=A[M(Hb)][M(Qb)];var R=P.indexOf(sc);if(R!=-1){B=Number(P.substring(R+1));P=P.substring(0,R)}Q=P+tc}catch(a){return}}var S;function T(){if(!s){s=true;if(!__gwt_stylesLoaded[uc]){var a=n.createElement(vc);__gwt_stylesLoaded[uc]=a;a.setAttribute(wc,xc);a.setAttribute(yc,t+uc);n.getElementsByTagName(zc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Ac,T,false)}if(S){clearInterval(S)}}}
if(n.addEventListener){n.addEventListener(Ac,function(){O();T()},false)}var S=setInterval(function(){if(/loaded|complete/.test(n.readyState)){O();T()}},50);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:bb});o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:$b,millis:(new Date).getTime(),type:Y});n.write(Bc)}
PrivacyPolicy();